export const data = [
    {
        end_year: 2016,
        intensity: 0,
        sector: "Manufacturing",
        topic: "growth",
        insight:
            "IEA Says Oil Prices May Fall Even Further Before Supply Fades in 2016",
        url: "http://www.bloomberg.com/news/articles/2015-07-10/iea-says-oil-price-may-fall-further-before-supply-fades-in-2016",
        region: "Northern America",
        start_year: "",
        impact: "",
        added: "July, 03 2016 06:00:25",
        published: "July, 10 2015 00:00:00",
        country: "United States of America",
        relevance: 4,
        pestle: "Economic",
        source: "Bloomberg Business",
        title:
            "U.S. production growth will slow to 300,000 barrels day next year from 900,000 a day in 2015.",
        likelihood: 0,
    },
    {
        end_year: "",
        intensity: 16,
        sector: "",
        topic: "growth",
        insight:
            "IEA Says Oil Prices May Fall Even Further Before Supply Fades in 2016",
        url: "http://www.bloomberg.com/news/articles/2015-07-10/iea-says-oil-price-may-fall-further-before-supply-fades-in-2016",
        region: "",
        start_year: 2016,
        impact: "",
        added: "July, 03 2016 06:00:25",
        published: "July, 10 2015 00:00:00",
        country: "",
        relevance: 4,
        pestle: "Economic",
        source: "Bloomberg Business",
        title: "Non-OPEC supply growth is expected to grind to a halt in 2016.",
        likelihood: 4,
    },
    {
        end_year: 2016,
        intensity: 3,
        sector: "Retail",
        topic: "export",
        insight:
            "IEA Says Oil Prices May Fall Even Further Before Supply Fades in 2016",
        url: "http://www.bloomberg.com/news/articles/2015-07-10/iea-says-oil-price-may-fall-further-before-supply-fades-in-2016",
        region: "",
        start_year: "",
        impact: "",
        added: "July, 03 2016 06:00:23",
        published: "July, 10 2015 00:00:00",
        country: "",
        relevance: 1,
        pestle: "Economic",
        source: "Bloomberg Business",
        title:
            "There will be no overall production growth outside the Organization of Petroleum Exporting Countries next year for the first time since 2008.",
        likelihood: 3,
    },
    {
        end_year: "",
        intensity: 2,
        sector: "",
        topic: "",
        insight: "Greenhouse gas",
        url: "https://en.wikipedia.org/wiki/Greenhouse_gas",
        region: "World",
        start_year: "",
        impact: "",
        added: "July, 03 2016 05:28:48",
        published: "July, 03 2016 00:00:00",
        country: "",
        relevance: 1,
        pestle: "",
        source: "Wikipedia",
        title:
            "Earth's surface temperature could exceed historical values as early as 2047.",
        likelihood: 2,
    },
]